version: '3.3'
services:
  simple-inference-client-app:
    image: $APP_NAME
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - INFERENCE_HOST=inference-server
      - INFERENCE_PORT=8501
      - MODEL_PATH=${MODEL_PATH}
    volumes:
      - /usr/lib/libvdostream.so.1:/usr/lib/libvdostream.so.1
      - acap_dl-models:/models:ro
      - /tmp:/output
      - /var/run/dbus:/var/run/dbus:rw

  inference-server:
    image: $INFERENCE_SERVER
    command: $INFERENCE_SERVER_COMMAND
    volumes:
      - /usr/acap-root/lib:/host/lib
      - acap_dl-models:/models:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket

  acap_dl-models:
    image: $MODEL_NAME
    build: .
    volumes:
      - acap_dl-models:/models

volumes:
  acap_dl-models: {}
