version: '3.3'
services:
  qr-decoder-app:
    image: ${APP_NAME}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100k"
    environment:
      - PYTHONUNBUFFERED=1
      - INFERENCE_HOST=unix:///tmp/acap-runtime.sock
    volumes:
      - inference-server:/tmp
  inference-server:
    image: axisecp/acap-runtime:1.3.1-aarch64-containerized
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100k"
    entrypoint: ["/opt/app/acap_runtime/acapruntime"]
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/parhand/parhandsocket:/run/parhand/parhandsocket
      - /usr/lib:/usr/lib
      - /usr/bin:/usr/bin
      - inference-server:/tmp
volumes:
  inference-server: {}
