version: '3.3'
services:
  object-detector-python:
    image: $APP_NAME
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100k"
    environment:
      - PYTHONUNBUFFERED=1
      - INFERENCE_HOST=inference-server
      - INFERENCE_PORT=8501
      - MODEL_PATH=/models/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
      - OBJECT_LIST_PATH=/models/coco_labels.txt
      - IMAGE_PATH=dog416.png
    volumes:
      - /usr/lib/libvdostream.so.1:/usr/lib/libvdostream.so.1
      - acap_dl-models:/models:ro
      - /tmp:/output
      - /var/run/dbus:/var/run/dbus:rw

  inference-server:
    image: axisecp/larod-inference-server:2.6.0-api.4.0-armv7hf-ubuntu20.04
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100k"
    command: /usr/bin/larod-inference-server -p 8501 -j 4
    volumes:
      - /usr/acap-root/lib:/host/lib
      - acap_dl-models:/models:ro
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket

  acap_dl-models:
    image: $MODEL_NAME
    volumes:
      - acap_dl-models:/models

volumes:
  acap_dl-models: {}
