# syntax=docker/dockerfile:1


FROM arm64v8/alpine

# Get SSD Mobilenet V2
ADD https://raw.githubusercontent.com/google-coral/test_data/master/movenet_single_pose_lightning_ptq_edgetpu.tflite models/
ADD https://raw.githubusercontent.com/google-coral/test_data/master/movenet_single_pose_lightning_ptq.tflite models/

CMD /bin/ls /models
