name: Build hello-world-python application

on:
  push:
    paths:
      - 'hello-world-python/**'
      - '!hello-world-python/README.md'
      - '.github/workflows/hello-world-python.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap-computer-vision-examples
      EXNAME: hello-world-python
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
        run: |
          cd $EXNAME
          docker build --no-cache --tag $imagetag .
