name: Build minimal-ml-inference application
on:
  push:
    paths:
      - 'minimal-ml-inference/**'
      - '!minimal-ml-inference/README.md'
      - '.github/workflows/minimal-ml-inference.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap-computer-vision-examples
      EXNAME: minimal-ml-inference
    strategy:
      matrix:
        include:
          - arch: armv7hf
            chip: cpu
          - arch: armv7hf
            chip: edgetpu
          - arch: aarch64
            chip: artpec8

    steps:
      - uses: actions/checkout@v2

      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}-${{ matrix.chip }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}-${{ matrix.chip }}:1.0
          modeltag: ${{ env.EXREPO }}_${{ env.EXNAME }}-${{ matrix.chip }}-model:1.0
        run: |
          cd $EXNAME
          docker run --rm --privileged multiarch/qemu-user-static --credential yes --persistent yes
          docker build --no-cache --build-arg CHIP=${{ matrix.chip }} --build-arg ARCH=${{ matrix.arch }} --tag $imagetag .
          docker build . -f Dockerfile.model -t $modeltag --build-arg ARCH=${{ matrix.arch }}
          docker image rm -f $imagetag