name: Build object-detector-python application

on:
  push:
    paths:
      - 'object-detector-python/**'
      - '!object-detector-python/README.md'
      - '.github/workflows/object-detector-python.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - chip: cpu
          - chip: artpec8
    env:
      EXREPO: acap-computer-vision-examples
      EXNAME: object-detector-python
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}-${{ matrix.chip }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}-${{ matrix.chip }}:1.0
          modeltag: ${{ env.EXREPO }}_${{ env.EXNAME }}-${{ matrix.chip }}-model:1.0
        run: |
          cd $EXNAME
          docker run --rm --privileged multiarch/qemu-user-static --credential yes --persistent yes
          docker build --no-cache --build-arg CHIP=${{ matrix.chip }} --tag $imagetag .
          docker build --file Dockerfile.model --tag $modeltag  .
