name: Build parameter-api-cpp application

on:
  push:
    paths:
      - 'parameter-api-cpp/**'
      - '!parameter-api-cpp/README.md'
      - '.github/workflows/parameter-api-cpp.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap-computer-vision-examples
      EXNAME: parameter-api-cpp
    strategy:
      matrix:
        include:
          - arch: armv7hf
          - arch: aarch64
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
        run: |
          cd $EXNAME
          docker build --no-cache --build-arg ARCH=${{ matrix.arch }} --tag $imagetag .
          docker image rm -f $imagetag
