name: Build parameter-api-python application

on:
  push:
    paths:
      - 'parameter-api-python/**'
      - '!parameter-api-python/README.md'
      - '.github/workflows/parameter-api-python.yml'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXREPO: acap-computer-vision-examples
      EXNAME: parameter-api-python
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build ${{ env.example }} application
        env:
          example: ${{ env.EXNAME }}
          imagetag: ${{ env.EXREPO }}_${{ env.EXNAME }}:1.0
        run: |
          cd $EXNAME
          docker run --rm --privileged multiarch/qemu-user-static --credential yes --persistent yes
          docker build --no-cache --tag $imagetag .
